---
title: "Mini-Project #2"
author: "Kiara Correa Acosta, Annabel Yim, Syrine Matoussi"
date: "March 24, 2019"
output:
  html_document:
    code_folding: hide
---

```{r, message = FALSE, warning = FALSE, include=FALSE, echo = TRUE}
library(tidyverse)
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
```


```{r, message = FALSE, warning = FALSE, echo = TRUE}
elections_florida <- 
  house_elections %>%
  filter(state == "FL") %>%
  select(fec_id, candidate_name, party, general_votes, ge_winner) 
# We are working with only swing states. First, we are using Florida, thus we filtered out the state Florida. Then, we only selected columns that may be relavent to our graph. Incumbent, runoff_votes, primary_votes, and other columns are not necessary for our purpose.

candidates_florida <- 
  candidates %>%
  filter(cand_office_state == "FL", cand_election_yr >= 2011 & cand_election_yr <= 2012) %>%
  select(cand_id, cand_election_yr, cand_office_state, cand_office_district)
# The candidates data set doesn't filter out election cycle 2011-2012, so we filtered out the years to be between 2011-2012. Also, Florida was also filtered. Then, we selected column that may be relavent to our graph. 

candidates_elections_florida <- 
  merge(elections_florida, candidates_florida, by.x="fec_id", by.y="cand_id") %>%
  filter(ge_winner == "W") 
# Because fec_id = cand_id, we used the merge function to combine both elections_florida and candidates_florida data sets. Also, since we want only the winners of the elections, we filtered out the winners using the filter function. 

```

```{r, message = FALSE, warning = FALSE, echo = TRUE}
committees_florida <-
  committees %>%
  select(cmte_id, cmte_name)
# Selecting the columns that are relavent for final data graphic. 

contributions_florida <-
  contributions %>% 
  filter(transaction_type != "24A") %>%
  select(cmte_id, transaction_type, name, transaction_amt, cand_id) 
# We are only looking at transactions that were made for the candidate, not opposed. Thus, filtering out transaction_type 24A. Then, selected columns that are relavent for final data graphic. 

committees_contributions_florida <- committees_florida %>%
  full_join(contributions_florida, by = "cmte_id") %>%
  group_by(cand_id) %>%
  summarize(total_transaction = sum(transaction_amt))
# joined committees_florida and contributions_florida by cmte_id. Then, in order find out the total transactions received by each candidate from different committees, grouped the joined data frame by cand_id, and then summarized the transaction amount to find the total transaction made per candidate.  
```

```{r, message = FALSE, warning = FALSE, echo = TRUE}
combined_candidates_contributions <-
  merge(candidates_elections_florida, committees_contributions_florida, by.x="fec_id", by.y="cand_id") %>%
  group_by(party, cand_office_state) %>%
  summarize(num_districts_won = n(), 
            total_transaction_per_party = sum(total_transaction)/1000000)
# In order to match the transaction amount to the candidates, merged the two data frames to get the information about the candidate and the transaction amount to be combined in one data frame. Then, in order to find how many districts were won by Democrats and Republicans, we grouped the data frame by party, and then found how many Democrats and Republicans won by using the summarize function by finding the number of rows that were either Democrats or Republicans. 
```


```{r, message = FALSE, warning = FALSE, echo = TRUE}
ggplot(data= combined_candidates_contributions, aes(y = num_districts_won , x = total_transaction_per_party, color= party, fill=party))+ geom_area(size=7)+labs(title= "Florida", face="bold",size=25)+labs(y= "number of districts that won")+labs(x= "contributions in millions per party")+scale_color_manual(values = c("blue4", "darkred"))+scale_fill_manual(values = c("blue4", "darkred"))+theme(panel.background = element_rect(fill = '#92BDD4'))+theme(plot.background = element_rect(fill = 'white'))+theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
```


```{r, message = FALSE, warning = FALSE, echo = TRUE}
elec_contrib <- function(state_arg){
elections_per_state <-
 house_elections %>%
 filter(state == state_arg) %>%
 select(fec_id, candidate_name, party, general_votes, ge_winner)

candidates_per_state <-
 candidates %>%
 filter(cand_office_state == state_arg, cand_election_yr >= 2011 & cand_election_yr <= 2012) %>%
 select(cand_id, cand_election_yr, cand_office_state, cand_office_district)

candidates_elections_per_state <-
 merge(elections_per_state, candidates_per_state, by.x="fec_id", by.y="cand_id") %>%
 filter(ge_winner == "W")

committees_per_state <-
 committees %>%
 select(cmte_id, cmte_name)

contributions_per_state <-
 contributions %>%
 filter(transaction_type != "24A") %>%
 select(cmte_id, transaction_type, name, transaction_amt, cand_id)

committees_contributions_per_state <- committees_per_state %>%
 full_join(contributions_per_state, by = "cmte_id") %>%
 group_by(cand_id) %>%
 summarize(total_transaction = sum(transaction_amt))

combined_candidates_contributions <-
 merge(candidates_elections_per_state, committees_contributions_per_state, by.x="fec_id", by.y="cand_id") %>%
 group_by(party, cand_office_state = state_arg) %>%
 summarize(num_districts_won = n(),
           total_transaction_per_party = sum(total_transaction)/1000000)}

# Same procedure for data wrangling, but in order to apply it to all the other swing states, a function was made to take in the state_arg argument. 

```


```{r, message = FALSE, warning = FALSE, echo = TRUE}
actual_states <- c("FL","CO","NV","OH","IA","MI","MN","NH","NC","WI","PA","VA")

my_data <- map_df(actual_states, elec_contrib) 

  ggplot(data= my_data, aes(y = num_districts_won , x = total_transaction_per_party, color= party, fill=party)) + facet_wrap(~cand_office_state, ncol = 4) + geom_area(size=2) + labs(y= "number of districts that won")+labs(x= "contributions in millions per party")+scale_color_manual(values = c("blue4", "darkred"))+scale_fill_manual(values = c("blue4", "darkred"))+theme(panel.background = element_rect(fill = '#92BDD4'))+theme(plot.background = element_rect(fill = 'white'))+theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + scale_y_continuous(limits = c(0, 20), breaks = c(0,5,10,15,20), expand = c(0, 0)) + scale_x_continuous(limits = c(0, 15), breaks = c(3, 6, 9, 12, 15), expand = c(0, 0))

```



^[[Link to the GitHub Repository](https://github.com/annabelyim/sds192-mp2.git)]

